# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

version: '3.4'

services:
  validator:
    depends_on:
      - remme-genesis
    volumes:
      - genesis_data:/genesis/batch
      - user_keys:/etc/sawtooth/keys
    environment:
      - REMME_START_MODE=genesis

  remme-genesis:
    container_name: remme_genesis
    image: remme/remme-core:latest
    volumes:
      - user_keys:/etc/sawtooth/keys
      - genesis_data:/genesis/batch
      - ../config/remme-client-config.toml:/config/remme-client-config.toml
      - ../config/remme-genesis-config.toml:/config/remme-genesis-config.toml
    environment:
      - REMME_START_MODE=genesis
    command: sh /root/remme/bash/genesis.sh

volumes:
  genesis_data:
