version = 1
disable_existing_loggers = false

[formatters.default]
format = "[%(asctime)s.%(msecs)03d [%(threadName)s] %(module)s %(levelname)s] %(message)s"
datefmt = "%H:%M:%S"

[handlers.main]
level = "ERROR"
formatter = "default"
class = "logging.FileHandler"
filename = "/var/log/rest-api-error.log"

[root]
level = "ERROR"
handlers = ["main"]
